name: Configure CI
description: Performs the initial configuration of the CI environment

runs:
  using: composite

  steps:
    - name: Set up Java
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # pin@v4.6.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # pin@v4.0.0
      with:
        gradle-version: '8.10'

    - name: Download Android dependencies
      run: ./gradlew androidDependencies
      shell: bash

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # pin@1.1.0