name: Configure CI
description: Performs the initial configuration of the CI environment

inputs:
  java:
    description: The Java version to use
    required: false
    default: '17'

runs:
  using: composite

  steps:
    - name: Set up Java
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # pin@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}
        cache: 'gradle'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # pin@v5
      with:
        gradle-version: wrapper
        cache-cleanup: on-success

    - name: Download dependencies
      run: ./gradlew androidDependencies
      shell: bash
