name: Configure CI
description: Performs the initial configuration of the CI environment

inputs:
  java:
    description: The Java version to use
    required: false
    default: '17'

runs:
  using: composite

  steps:
    - name: Set up Java
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # pin@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java }}
        cache: 'gradle'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # pin@v4
      with:
        gradle-version: wrapper
        cache-cleanup: on-success

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation-action@ed408507eac070d1f99cc633dbcf757c94c7933a # pin@v4

    - name: Download dependencies
      run: ./gradlew androidDependencies --no-daemon
      shell: bash
