name: Android MP1.0

on:
  push:
    branches: [ "90020241112213250446403000000000000001223372060384138274" ]
  pull_request:
    branches: [ "90020241112213250446403000000000000001223372060384138274" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
